app.security.swagger-public=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

app.cors.allowed-origins=https://erp.suaempresa.com.br


api.security.token.issuer=${JWT_ISSUER}

api.security.token.expiration-minutes=${JWT_EXPIRATION_MINUTES}

api.security.refresh-token.expiration-days=${REFRESH_TOKEN_EXPIRATION_DAYS}

api.security.refresh-token.cleanup-cron=${REFRESH_TOKEN_CLEANUP_CRON}

app.security.login.max-failed-attempts=${LOGIN_MAX_FAILED_ATTEMPTS}
app.security.login.lock-minutes=${LOGIN_LOCK_MINUTES}