app.security.swagger-public=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

app.cors.allowed-origins=http://localhost:4200


api.security.token.issuer=erp-api-dev

api.security.token.expiration-minutes=480